theme:
  light: [flatly, _quarto/i2ml_theme.scss]
  dark: [darkly, _quarto/i2ml_theme.scss]
format: 
  html:
    toc: true
    code-fold: false
    mathspec: true
    latex_engine: pdflatex
    include-before-body: _quarto/mathjax.tex
jupyter: python3
knitr:
  opts_chunk: 
    collapse: true
execute: 
    enabled: true
notebook-links: global
